networks:
  local:

services:
  # Nginx
  nginx:
    image: nginx:1.25.2-alpine
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - frontend
    networks:
      - local

  # Frontend (Nuxt3)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000"
    depends_on:
      - backend
    networks:
      - local

  # Backend (Express + Prisma)
  backend:
    build:
      context: ./backend
    ports:
      - "3001"
    environment:
      - DATABASE_URL=postgresql://tgwifi:iklcvnfqugxe@db:5432/tgwifi
    depends_on:
      - db
    networks:
      - local

  # PostgreSQL Database
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tgwifi
      POSTGRES_PASSWORD: iklcvnfqugxe
      POSTGRES_DB: tgwifi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local

volumes:
  postgres_data:
